namespace iTunda.Api.Dtos;

public record ProduceResponse(
    int Id,
    string Name,
    string Category,
    string? Description,
    decimal Price,
    string Unit,
    double QuantityAvailable,
    string? ImagePath,
    DateTime? PlantingDate,
    DateTime? HarvestDate,
    DateTime? ExpiryDate,
    DateTime? AvailableFrom,
    bool IsExportReady,
    string? GradeQuality,
    int FarmerProfileId,
    string FarmerName,
    string? FarmerPhone,
    string? FarmerImage,
    string? FarmName,
    string? County,
    string? SubCounty,
    string? Town,
    double? FarmLatitude,
    double? FarmLongitude,
    double FarmerRating,
    int FarmerOrdersFulfilled,
    string? Region,
    string? Country,
    string? CountryCode,
    int Zone,
    string ImageUrl,
    List<string> Gallery,
    string IconUrl,
    bool IsDraft,
    string DeliveryScope,
    string? FarmerUsername = null);

public record CreateProduceRequest(
    string Name,
    string Category,
    string? Description,
    decimal Price,
    string Unit,
    double QuantityAvailable,
    string? ImagePath,
    DateTime? HarvestDate,
    DateTime? ExpiryDate,
    DateTime? AvailableFrom,
    bool IsExportReady = false,
    string? GradeQuality = null,
    DateTime? PlantingDate = null,
    double? FarmLatitude = null,
    double? FarmLongitude = null,
    List<string>? Images = null,
    bool IsDraft = false,
    string? DeliveryScope = null);
